/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anakodingperpustakaan.main;

import anakodingperpustakaan.config.Database;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fandi
 */
public class category extends javax.swing.JInternalFrame {

    /**
     * Creates new form category
     */
    public category() {
        initComponents();
        selectData();
    }

     public void selectData()
    {
        String column[] = {"ID", "Name", "Description"};
        DefaultTableModel dtm = new DefaultTableModel(null, column);
        String SQL   = "SELECT * from category";
        ResultSet rs = Database.executeQuery(SQL);
        
        try{ 
            while(rs.next()){
                String ID           = rs.getString(1);
                String Name         = rs.getString(2);
                String Description  = rs.getString(3);
                String data[]       = {ID, Name, Description};
                dtm.addRow(data);
            }
            
            
        } catch (SQLException ex){
           Logger.getLogger(category.class.getName()).log(Level.SEVERE, null, ex);
        }
        categoryTable.setModel(dtm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        categoryName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categoryDescription = new javax.swing.JTextArea();
        categorySubmitBtn = new javax.swing.JButton();
        categoryResetBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoryTable = new javax.swing.JTable();
        categorySearch = new javax.swing.JTextField();
        categoryDeleteBtn = new javax.swing.JButton();
        categoryEditBtn = new javax.swing.JButton();
        categorySearchBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Category");
        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(810, 508));
        setPreferredSize(new java.awt.Dimension(1110, 708));

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setText("Category Name");

        jLabel2.setText("Category Description");

        categoryDescription.setColumns(20);
        categoryDescription.setRows(5);
        jScrollPane1.setViewportView(categoryDescription);

        categorySubmitBtn.setText("SUBMIT");
        categorySubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorySubmitBtnActionPerformed(evt);
            }
        });

        categoryResetBtn.setText("RESET");
        categoryResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(categorySubmitBtn)
                        .addGap(18, 18, 18)
                        .addComponent(categoryResetBtn))
                    .addComponent(categoryName)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1017, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(categoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorySubmitBtn)
                    .addComponent(categoryResetBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));

        categoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        categoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(categoryTable);

        categoryDeleteBtn.setText("DELETE");
        categoryDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryDeleteBtnActionPerformed(evt);
            }
        });

        categoryEditBtn.setText("EDIT");
        categoryEditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryEditBtnActionPerformed(evt);
            }
        });

        categorySearchBtn.setText("SEARCH");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(categorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categorySearchBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                        .addComponent(categoryDeleteBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(categoryEditBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorySearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryDeleteBtn)
                    .addComponent(categoryEditBtn)
                    .addComponent(categorySearchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(557, 557, 557)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categorySubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorySubmitBtnActionPerformed
        if("".equals(categoryName.getText()) )
        {
            JOptionPane.showMessageDialog(this, "Category Name can't be empty", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String SQL = "INSERT INTO category (name, description)"
                        + "VALUES ('"+ categoryName.getText()+"', '"+categoryDescription.getText()+"')";
            int status = Database.execute(SQL);
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Added Category Success", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Failed Add Category", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_categorySubmitBtnActionPerformed

    private void categoryDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryDeleteBtnActionPerformed
       int line = categoryTable.getSelectedRow();
       if(line != -1){
           String ID    = categoryTable.getValueAt(line, 0).toString();
           String SQL   = "DELETE FROM t_siswa WHERE id = '"+ID+"'";
           int status   = Database.execute(SQL);
           
           if(status == 1){
               JOptionPane.showMessageDialog(this, "Deleted category success", "Success", JOptionPane.INFORMATION_MESSAGE);
               selectData();
           }else{
               JOptionPane.showMessageDialog(this, "Upps !! wrong delete category", "Error", JOptionPane.WARNING_MESSAGE);
           }
       }else{
           JOptionPane.showMessageDialog(this, "Chose the line first !!", "Error", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_categoryDeleteBtnActionPerformed

    private void categoryResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryResetBtnActionPerformed
        categoryName.setText("");
        categoryDescription.setText("");
    }//GEN-LAST:event_categoryResetBtnActionPerformed

    private void categoryEditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryEditBtnActionPerformed
        
        int line = categoryTable.getSelectedRow();
        
         if(line != -1){
           String ID    = categoryTable.getValueAt(line, 0).toString();
           
           if("".equals(categoryName.getText()) )
        {
            JOptionPane.showMessageDialog(this, "Category Name can't be empty", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            
            String SQL = "UPDATE category SET "
                        + "name = '"+categoryName.getText()+"', "
                        + "description ='"+categoryDescription.getText()+"'"
                        + "WHERE id = '"+ID+"'";
            
            int status = Database.execute(SQL);
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Updated category success", "Success", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else{
                JOptionPane.showMessageDialog(this, "Updated category failed", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
           
       }else{
           JOptionPane.showMessageDialog(this, "Chose the line first !!", "Error", JOptionPane.WARNING_MESSAGE);
       }
        
        
        
        
    }//GEN-LAST:event_categoryEditBtnActionPerformed

    private void categoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoryTableMouseClicked
       
        int line = categoryTable.getSelectedRow();
        if(line != -1)
        {
            categoryName.setText(categoryTable.getValueAt(line, 1).toString());
            categoryDescription.setText(categoryTable.getValueAt(line, 2).toString());
        }
    }//GEN-LAST:event_categoryTableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton categoryDeleteBtn;
    private javax.swing.JTextArea categoryDescription;
    private javax.swing.JButton categoryEditBtn;
    private javax.swing.JTextField categoryName;
    private javax.swing.JButton categoryResetBtn;
    private javax.swing.JTextField categorySearch;
    private javax.swing.JButton categorySearchBtn;
    private javax.swing.JButton categorySubmitBtn;
    private javax.swing.JTable categoryTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
